## 为什么要学习pytorch

tensorflow的学习曲线陡峭

pytorch出自facebook

PyTorch 可以当做 NumPy 用

静态图 vs 动态图


最新版本全部使用tensor就可以

numpy能实现的东西，在pytorch基本可以实现

torch.randn()=numpy.random.randn()

torch.max()=np.max()

torch.zeros()=np.zeros()


如果不能实现,Tensor与numpy之间的可以相互转化

tensor.numpy()



In [1]:
import numpy as np
import torch
import torch.nn as nn
print(torch.__version__)

1.1.0


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [3]:
# python struct to torch tensor
temp=[0, 1, 2, 3, 4, 5, 6]
x = torch.tensor(temp, dtype=torch.float, device=device)
x

tensor([0., 1., 2., 3., 4., 5., 6.])

In [ ]:
#gpu/cpu
x = torch.tensor(temp).cuda()
x = x.cpu()

In [ ]:
x=x.long()
x=x.float()

## numpy reshape  squeeze expand_dims

In [4]:
a  = np.arange(10)
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [5]:
#a=a.reshape(1,-1)
#a.reshape(1,10)
a=a.reshape(5,2,1)
print(a)
print(a.shape)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]
(5, 2, 1)


In [7]:
b = np.squeeze(a)
print(b)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [8]:
a  = np.arange(10)
a=a.reshape(5,1,2)
print(a.shape)

(5, 1, 2)


In [9]:
b = np.squeeze(a)#b=a.reshape(5,2)
print(b)
print(b.shape)
#np.squeeze(e,axis = 0,1,2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [10]:
#expand_dims
a  = np.arange(10)
print("a",a.shape)
b = np.expand_dims(a, axis=0)
print("b axis=0",b.shape)
c = np.expand_dims(a, axis=1)
print("c axis=1",c.shape)

a (10,)
b axis=0 (1, 10)
c axis=1 (10, 1)


## pytorch reshape  squeeze unsqueeze

In [11]:
x  = torch.arange(0,10)
print("x",x)
print("x",x.shape)
b = x.unsqueeze(0)
print("b axis=0",b.shape)
c = torch.unsqueeze(x,1)
print("c axis=1",c.shape)


x tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x torch.Size([10])
b axis=0 torch.Size([1, 10])
c axis=1 torch.Size([10, 1])


In [12]:
d=c.squeeze(1)
print("d",d.shape)
d=c.squeeze()
print("d",d.shape)


d torch.Size([10])
d torch.Size([10])


In [13]:
d=b.squeeze()
print("d",d.shape)

d torch.Size([10])


In [48]:
import torch.nn.functional as F
m = nn.Sigmoid()

loss = nn.BCEWithLogitsLoss()
temp=[0, 1, 2,0, 1, 2,0, 1]
input =torch.tensor(temp, dtype=torch.float, requires_grad=True)
#input = torch.randn(3, requires_grad=True)
target = torch.tensor([0,1,1,0,1,1,0,1], dtype=torch.float)
lossinput = input
output = loss(lossinput, target)


print(lossinput.shape)

print(target.shape)

print(output)



torch.Size([8])
torch.Size([8])
tensor(0.4091, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


## logist regression

$$y(z) = \frac{1}{1 + exp(-\theta^T z)}$$

nn.BCELoss
$$
        \ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
        l_n = - w_n \left[ y_n \cdot \log x_n + (1 - y_n) \cdot \log (1 - x_n) \right],
 $$ 
 

In [ ]:
import torch.nn.functional as F   # 激励函数库

feature_num=100

class LogistRegression(torch.nn.Module):
    def __init__(self):
        super(LogistRegression, self).__init__()
        self.linear = torch.nn.Linear(feature_num, 1)
    def forward(self, x):
        z=self.linear(x)
        y_pred = F.sigmoid(z)
        return y_pred
    def loss(y_pred,label):#Binary Cross Entropy
        criterion = torch.nn.BCELoss(size_average=True)
        return criterion(y_pred,label)

nn.CrossEntropyLoss() 自带sigmod，不需要加