# Python Numpy Review

主要复习numpy

tutor:  `chongjiujin # gmail.com`

```
if you have any question in python or pytorch:

    print(add personal weichat:flypython)
   ```

# List Slicing

List elements can be accessed in convenient ways.

Basic format: some_list[start_index:end_index]

In [1]:
numbers = [0, 1, 2, 3, 4, 5, 6]
numbers

[0, 1, 2, 3, 4, 5, 6]

In [2]:
numbers[0:3]

[0, 1, 2]

In [4]:
numbers[:4]

[0, 1, 2, 3]

In [8]:
numbers[5:]

[5, 6]

In [7]:
numbers[:]

[0, 1, 2, 3, 4, 5, 6]

In [9]:
# Negative index wraps around
numbers[-1]

6

In [10]:
numbers[-3:]

[4, 5, 6]

In [14]:
# Can mix and match
numbers[1:-10]

[]

# Numpy python矩阵计算库


Optimized library for matrix and vector computation.

用于矩阵和向量



Makes use of C/C++ subroutines and memory-efficient data structures.

底层是C/C++编译的，效率更高

(Lots of computation can be efficiently represented as vectors.)

**Main data type: `np.ndarray`**

This is the data type that you will use to represent matrix/vector computations.
这个数据结构是用来放矩阵/向量的

Note: constructor function is `np.array()`

 `np.array()`初始化函数


In [15]:
import numpy as np#导入库

In [18]:
x = np.array([1,2,3])#一维向量
x
x.shape

(3,)

In [20]:
y = np.array([[3,4,5],[6,7,8]])#二维矩阵
y.shape

(2, 3)

In [21]:
y = np.array([[1],[2],[3]])#每个框是增加一个维度
y.shape

(3, 1)

# np.ndarray Operations 操作函数

Reductions: `np.max`, `np.min`, `np.argmax`, `np.sum`, `np.mean`, …

Always reduces along an axis! (Or will reduce along all axes if not specified.)

(You can think of this as “collapsing” this axis into the function’s output.)

In [22]:
x = np.array([1,2,3])#一维向量
x.max()#np.max(x)
#x.min()
#x.sum()
#x.mean()


3

In [25]:
y = np.array([[3,4,5],[6,7,8]])#按维度取最大值
#np.max(y,axis = 1)
np.max(y, axis = 1, keepdims = True)
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html#numpy.amax

array([[5],
       [8]])

# 基本矩阵运算


`np.dot`矩阵点乘
$$ np.dot(v,w)=v^T w $$
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html?highlight=dot#numpy.dot

`np.multiply` 在 np.array 中重载为元素乘法，在 np.matrix 中重载为矩阵乘法

https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html


我们这里只讨论一维向量

In [26]:
#np.dot点乘

x=np.array([1,2,3])#一维向量
y=np.array([1,2,3])#一维向量
np.dot(x,y)
#

14

In [27]:
sum(x.T*y)

14

In [28]:
x=np.array([1,2,3])#一维向量
np.multiply(x,x)

array([1, 4, 9])

# Indexing  索引

In [29]:
#基本同list
x = np.array([1,2,3])#一维向量
x[x > 2]


array([3])

In [30]:
index=[2,1,0]#按索引排序
x[index]

array([3, 2, 1])

# 矩阵遍历

有时候需要遍历矩阵里所有的向量

In [31]:
y = np.array([[3,4,5],[6,7,8]])#二维矩阵
print(y)


[[3 4 5]
 [6 7 8]]


In [32]:
#默认按第1维度遍历
for y1 in y:
    print(y1)
    print("-----")

[3 4 5]
-----
[6 7 8]
-----


In [33]:
#按指定维度遍历
d1,d2= y.shape
print(d1,d2)

2 3


In [34]:
for d in range(d2):
    print(d,y[:,d])

0 [3 6]
1 [4 7]
2 [5 8]


# Efficient Numpy Code
尽量用Numpy的特性提升效率

In [36]:
x = np.array([[3,4,5],[6,7,8]])#二维矩阵
y = np.array([[1,2,3],[9,0,10]])#二维矩阵

In [37]:
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        x[i,j] **= 2
x

array([[ 9, 16, 25],
       [36, 49, 64]])

In [38]:
x **= 2
x

array([[  81,  256,  625],
       [1296, 2401, 4096]])

# 全0 和全 1 矩阵

In [40]:
z=np.zeros((2,))
for i in range(x.shape[0]):
    x1=x[i]
    y1=y[i]
    z[i]=np.dot(x1,y1)
z

array([1.30950800e+06, 1.82888704e+08])

In [41]:
z=np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

# 矩阵和常数计算以及 Broadcasting广播

In [42]:
x = np.array([[3,4,5],[6,7,8],[1,2,3]])#二维矩阵
x.shape

(3, 3)

In [43]:
x+2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 3,  4,  5]])

In [44]:
x*2

array([[ 6,  8, 10],
       [12, 14, 16],
       [ 2,  4,  6]])

In [52]:
y=np.array([[2],[4],[8]])
y.shape

(3, 1)

In [46]:
x+y

array([[ 5,  6,  7],
       [10, 11, 12],
       [ 9, 10, 11]])

## 矩阵变换

In [48]:
z=np.array([[2, 4, 8]])
z.shape

(1, 3)

In [50]:
z=y.reshape(-1,1)
z.shape

(3, 1)

In [53]:
z=y.T
z.shape

(1, 3)

In [54]:
x*z

array([[ 6, 16, 40],
       [12, 28, 64],
       [ 2,  8, 24]])

# 思考题
y=np.array([[2],[4],[8]])

(y + y.T)是什么


# 如果对操作有不确定，开一个jupyter notebook，测试后使用